baseURL: https://example.com
languageCode: en-us
title: Turning Points For Women Study
theme: "vanilla-bootstrap-hugo-theme"
googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Study Home
    pre: home
    url: /
    weight: 1
  - name: Blog
    pre: edit
    url: /post/
    weight: 4
  - name: Contact Us
    pre: send
    url: /SayHello/
    weight: 7
  - name: Our Team
    pre: users
    url: /team/
    weight: 2
  - name: Study History
    pre: clock
    url: /history/
    weight: 3
  - name: Documentation
    pre: github
    url: /github/
    weight: 6
  - name: Data
    pre: database
    url: /data/
    weight: 5

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: welcome home
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: true
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    startLevel: 2
